function generateDocument(characters, document) {
	// create a hashmap of { char: count } from characters
	const charMap = charactersToMap(characters);
	// check if document can be generated by characters
	const canBeGenerated = checkGenerationAbility(charMap, document);
  return canBeGenerated;
}

function charactersToMap(characters) {
	const map = {};
	for (let c of characters) {
		if (!map[c]) {
			map[c] = 0;
		}
		map[c] += 1;
	}
	return map;
}

function checkGenerationAbility(charMap, document) {
	// for every letter in document, remove its complement from charMap
	// any letter in document and not in charMap fails generation
	for (let c of document) {
		if (!charMap[c]) {
			return false;
		}
		charMap[c] -= 1;
	}
	return true;
}

// Do not edit the line below.
exports.generateDocument = generateDocument;

